"""firsts migrations

Revision ID: 0ea16e0af26e
Revises: a3bd5a59ba36
Create Date: 2024-07-07 16:41:50.858829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea16e0af26e'
down_revision = 'a3bd5a59ba36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soutenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('fichier', sa.String(length=200), nullable=True),
    sa.Column('lieu_stage', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('cahier_charge', sa.String(length=200), nullable=True),
    sa.Column('is_theme_valide', sa.Boolean(), nullable=True),
    sa.Column('is_binome_valide', sa.Boolean(), nullable=True),
    sa.Column('choix1_id', sa.Integer(), nullable=True),
    sa.Column('choix2_id', sa.Integer(), nullable=True),
    sa.Column('maitre_memoire_id', sa.Integer(), nullable=True),
    sa.Column('annee_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['annee_id'], ['annee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['choix1_id'], ['enseignant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['choix2_id'], ['enseignant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maitre_memoire_id'], ['enseignant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_foreign_key(None, 'appartenir', 'soutenance', ['soutenance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('jury_examinateur_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_president_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_rapporteur_id_fkey', 'jury', type_='foreignkey')
    op.create_foreign_key(None, 'jury', 'enseignant', ['president_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['rapporteur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['examinateur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'planification', 'soutenance', ['thesis_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planification', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.create_foreign_key('jury_rapporteur_id_fkey', 'jury', 'enseignant', ['rapporteur_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_president_id_fkey', 'jury', 'enseignant', ['president_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_examinateur_id_fkey', 'jury', 'enseignant', ['examinateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'appartenir', type_='foreignkey')
    op.drop_table('soutenance')
    # ### end Alembic commands ###
